server {
    listen 80;

    # Interface do Monitoramento-262
    # Agora o alias aponta para a subpasta que o Docker criou no container
    location /ping {
        alias /usr/share/nginx/html/monitor-262/;
        index index.html;
    }

    # API do Monitoramento
    # O JavaScript do seu index.html continuará buscando em localhost/status
    location /status {
        proxy_pass http://api-monitor:8000/status;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Preparado para o Afinador de Guitarra no futuro
    location /afinador {
        alias /usr/share/nginx/html/afinador/;
        index index.html;
    }
}